version: '3'

services:
  mysql:
    image: mysql:latest
    volumes:
      - ./database_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "playground"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"